services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autostore
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  autostore_api:
    build: .
    env_file:
      - .env
      - .env.example
    container_name: autostore_api
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-dev-secret-change-me}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=autostore
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - EXCHANGE_RATE_API_KEY=74750f7ecce959162d511e722a901a64
    ports:
      - "3000:3000"
    command: ["sh", "-c", "node dist/scripts/seed-admin.js && node dist/main.js"]

volumes:
  db_data:
